[build.environment]
NODE_VERSION = "22.14.0" # - latest NODE version
NPM_VERSION = "11.3.0"   # - latest NPM version
YARN_VERSION = "1.22.22" # - latest YARN version

[build]
publish = "public"
command = "npm run build"

[context.production]
command = "npm run build:prod"

[context.staging]
command = "npm run build:staging"
