[build.environment]
NODE_VERSION = "24.15.0" # - latest NODE version
NPM_VERSION = "11.12.1"  # - latest NPM version
YARN_VERSION = "4.14.1"  # - latest YARN version
COREPACK_ENABLE = "1"

[build]
publish = "public"
command = "yarn build"
functions = "netlify/functions"

[context.production]
command = "yarn build:prod"

[context.staging]
command = "yarn build:staging"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["resend"]
