[build.environment]
NODE_VERSION = "22.17.1" # - latest NODE version
NPM_VERSION = "11.5.1"   # - latest NPM version
YARN_VERSION = "1.22.22" # - latest YARN version

[build]
publish = "public"
command = "npm run build"
functions = "netlify/functions"

[context.production]
command = "npm run build:prod"

[context.staging]
command = "npm run build:staging"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["resend"]
